version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_push:
    docker:
      - image: circleci/php:7-apache
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7
      - run: 
          command: php -v
      # - run: 
      #     command: docker-php-ext-enable xdebug
      - run: 
          command: pwd
      - run:
          command: |
            docker run --rm --mount type=bind,source=/home/circleci/project,target=/app jekkos/composer composer install
            docker run --rm --mount type=bind,source=/home/circleci/project,target=/app jekkos/composer php bin/install.php translations develop
            sed -i "s/'\(dev\)'/'$rev'/g" application/config/config.php
            version=$(grep application_version application/config/config.php | sed "s/.*=\s'\(.*\)';/\1/g")
            echo "$version-$branch-$rev" 
            npm version "$version-$branch-$rev" --force || true
            docker run --rm -it -v . -w /app opensourcepos/node-grunt-bower
              sh -c "npm install && bower install && grunt package"
            docker build . --target ospos -t ospos
            docker-compose -f docker-compose.test.yml up --abort-on-container-exit
      - run:
          name: Build Docker image
          command: docker build -t hahayusuf/opensourcepos:${CIRCLE_SHA1} .



      # - run:
      #     name: Push Docker image to Docker Hub
      #     command: |
      #       docker login -u your-dockerhub-username -p your-dockerhub-password
      #       docker push your-dockerhub-username/your-image-name:${CIRCLE_SHA1}

workflows:
  build-workflow:
    jobs:
      - build_and_push:
          context: docker-secrets
          # filters:
          #   branches:
          #     only: 
          #       - master
