version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build_and_push:
    docker:
      - image: circleci/php:7-apache
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7
      - run: 
          command: php -v
      - run: 
          command: docker-php-ext-enable xdebug
      - run: 
          command: php -v
      - run:
          name: Build Docker image
          command: docker build -t hahayusuf/opensourcepos:${CIRCLE_SHA1} .

      # - run:
      #     name: Push Docker image to Docker Hub
      #     command: |
      #       docker login -u your-dockerhub-username -p your-dockerhub-password
      #       docker push your-dockerhub-username/your-image-name:${CIRCLE_SHA1}

workflows:
  build-workflow:
    jobs:
      - build_and_push:
          context: docker-secrets
          # filters:
          #   branches:
          #     only: 
          #       - master
